### ISSUE TITLE
调用`send_image`时, ws链接异常关闭

### ISSUE THREAD

**Issue by KimigaiiWuyi** [JustUndertaker/adapter-ntchat#2]
```python
async def send_abyss_info(
    event: TextMessageEvent,
    matcher: Matcher,
    args: Tuple[Any, ...] = RegexGroup(),
):
    im: bytes = await somethings()
    if isinstance(im, bytes):
        await matcher.finish(MessageSegment.image(im))
```

NoneBot2端报错如下

```sh
11-08 23:15:36 [INFO] ntchat | 开始执行[查询深渊信息]
11-08 23:15:36 [INFO] ntchat | [查询深渊信息]参数: (None, None, None, None, None, 'sy', None, None, None, None)
11-08 23:15:36 [INFO] ntchat | [查询深渊信息]uid: 100740568
11-08 23:15:36 [INFO] ntchat | [查询深渊信息]深渊期数: 1
11-08 23:15:36 [INFO] ntchat | [查询深渊信息]深渊层数: None
11-08 23:15:38 [INFO] ntchat | [查询深渊信息]绘图已完成,等待发送!
11-08 23:15:38 [DEBUG] nonebot | ntchat | Calling API send_image
11-08 23:15:48 [WARNING] nonebot | ntchat | WebSocket for Bot wxid_rh3e4aoi9cta22 closed by peer
11-08 23:15:48 [INFO] websockets | connection closed
11-08 23:15:58 [INFO] uvicorn | ('127.0.0.1', 62595) - "WebSocket /ntchat/ws" [accepted]
11-08 23:15:58 [INFO] nonebot | ntchat | Bot wxid_rh3e4aoi9cta22 connected
11-08 23:15:58 [INFO] websockets | connection open
11-08 23:15:58 [INFO] ntchat | 检查遗留信息...
11-08 23:16:08 [DEBUG] nonebot | ntchat | Calling API send_text
11-08 23:16:08 [ERROR] ntchat | 获取查询深渊信息信息错误
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\44483\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\44483\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "C:\Users\44483\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\44483\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\44483\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "C:\Users\44483\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\44483\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\44483\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\44483\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\44483\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\44483\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\44483\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\message.py", line 146, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
  File "C:\Users\44483\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\message.py", line 196, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\44483\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\matcher.py", line 668, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\44483\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\matcher.py", line 635, in simple_run
    await handler(
  File "C:\Users\44483\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\dependencies\__init__.py", line
 92, in __call__
    return await self.call(**values)
> File "G:\ntchat\.\ntchat\plugins\GenshinUID\GenshinUID\utils\exception\handle_exception.py", line 32, in inner
    await func(**kwargs)
  File "G:\ntchat\.\ntchat\plugins\GenshinUID\GenshinUID\genshinuid_abyss\__init__.py", line 101, in send_abyss_info
    await matcher.finish(MessageSegment.image(im))
  File "C:\Users\44483\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\matcher.py", line 464, in finish
    await cls.send(message, **kwargs)
  File "C:\Users\44483\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\matcher.py", line 449, in send
    return await bot.send(event=event, message=_message, **kwargs)
  File "C:\Users\44483\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\adapters\ntchat\bot.py", line 115, in send
    return await self.__class__.send_handler(self, event, message, **kwargs)
  File "C:\Users\44483\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\adapters\ntchat\bot.py", line 76, in send
    return await asyncio.gather(*task)
  File "C:\Users\44483\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\adapter\bot.py", line 117, in call_api
    raise exception
  File "C:\Users\44483\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\adapter\bot.py", line 94, in call_api
    result = await self.adapter._call_api(self, api, **data)
  File "C:\Users\44483\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\adapters\ntchat\adapter.py", line 106, in _call_api
    await self._result_store.fetch(bot.self_id, seq, timeout)
  File "C:\Users\44483\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\adapters\ntchat\store.py", line
 36, in fetch
    raise NetworkError("WebSocket API call timeout") from None
nonebot.adapters.ntchat.exception.NetworkError: <NetWorkError message=WebSocket API call timeout>
```

ntchat-client端报错如下

```sh
11-08 23:15:36 [DEBUG] ntchat_client | websocket - 向ws发送消息：{"data": {"at_user_list": [], "from_wxid": "wxid_********", "is_pc": 0, "msg": "sy", "msgid": "5043741867263393735", "room_wxid": "43586179708@chatroom", "timestamp": 1667920532, "to_wxid": "43586179708@chatroom", "wx_type": 1}, "type": 11046}
11-08 23:15:58 [ERROR] ntchat_client | websocket - ws链接异常关闭：
11-08 23:15:58 [INFO] ntchat_client | websocket - 正在连接到：ws://127.0.0.1:8080/ntchat/ws
11-08 23:15:58 [SUCCESS] ntchat_client | websocket - ws已成功连接！
11-08 23:16:08 [SUCCESS] ntchat_client | websocket - 收到ws消息：{"action": "send_text", "params": {"content": "发生错误 <NetWorkError message=WebSocket API call timeout
11-08 23:16:08 [DEBUG] ntchat_client | wechat - 调用接口：send_text，参数：{'content': '发生错误 <NetWorkError message=WebSocket API call timeout>，请检查后台输出。', 'to_wxid': '43586179708@chatroom'}
11-08 23:16:08 [DEBUG] ntchat_client | websocket - 向ws发送消息：{"status": 200, "msg": "调用成功", "data": true, "echo": "2"}
```

**Comment by JustUndertaker** [comment]
大概知道原因了，大概率是发送图片超时导致ws关闭，后续会在ntchat_client修复。

**Comment by JustUndertaker** [comment]
> 大概知道原因了，大概率是发送图片超时导致ws关闭，后续会在ntchat_client修复。

原因是ws缓存设置大小问题，默认为1mb，目前已修复。
